# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTUwMTdjYzc2OWE3MDIzMDJlYWYxZmIwM2NlZDBlNmI5YzMxMjY0N2EyZGJkYTE0OTA1YjUwZDlhMjQ1MzJhZjQxZjMzNmM4NzZjZjBhZjY5OTExNmQ4Y2VlYjM3Zjc2Zjc4ZGEwYjE2NWZlMTZhMDIzMDU4MzczODA4NzhmZDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
